In [1]:
import pickle
import numpy as np
ACTIONS = ['UP', 'RIGHT', 'DOWN', 'LEFT', 'WAIT', 'BOMB']
ACTION_TO_INT = {'UP':0, 'RIGHT':1, 'DOWN':2, 'LEFT':3, 'WAIT':4, 'BOMB':5}

In [2]:
ACTIONS[ACTION_TO_INT['BOMB']]

'BOMB'

In [3]:
def get_direction_from_to(p1, p2):
    v = get_vector_from_to(p1, p2)
    if (v[0] == None) or (v[1] == None):
        return (None, None)
    if v[0] < 0:
        a = -1
    elif v[0] > 0: 
        a = 1
    else: 
        a = 0

    if v[1] < 0:
        b = -1
    elif v[1] > 0: 
        b = 1
    else: 
        b = 0
    return (a,b)

def get_nearest_coin(state:dict):
    # TODO catch case in which there are no more coins left
    coins = state['coins'] 
    _, _, _, (x,y) = state['self']
    minDistToCoin = np.inf
    nearestCoin = (None, None)
    for coin in coins:
        dist = manhattenDist((x,y), coin)
        if dist < minDistToCoin:
            minDistToCoin = dist
            nearestCoin = coin
    return nearestCoin

def get_vector_from_to(p1, p2):
    try:
        return (p2[0]-p1[0], p2[1]-p1[1])
    except:
        (None,None)

def get_longest_direction_from_to(p1, p2):
    v = get_vector_from_to(p1, p2)
    if (v[0] == None) or (v[1] == None):
        return (None, None)
    if np.abs(v[0]) > np.abs(v[1]):
        if v[0] > 0:
            return (1, 0)
        else: 
            return (-1,0)
    else:
        if v[1] > 0:
            return (0, 1)
        else: 
            return (0,-1)

def manhattenDist(p1, p2):
    try:
        return np.abs( p1[0]-p2[0] ) + np.abs( p1[1]-p2[1] )
    except:
        return None

In [4]:
get_direction_from_to((1,1), (1,2))

(0, 1)

In [5]:
get_vector_from_to((1,1), (1,2))


(0, 1)

In [6]:
channels = []
(x,y) = (14,15)
nearest_coin = (1, 1)
channels.append((x,y))                                      # add own position
channels.append( get_longest_direction_from_to( (x,y), nearest_coin ) )
channels

[(14, 15), (0, -1)]

In [7]:
with open("my-saved-model.pt", "rb") as file:
    model:dict = dict(pickle.load(file))

In [8]:
for key in sorted(model.keys()):
    #print(key)
    action = model[key].argmax()
    print(key, ACTIONS[action], action)
    print(model[key] )
    print()


[ 0  1  0 -1  0  1] RIGHT 1
[ -1.1          0.97527448  -1.1         -0.60844985 -10.1
 -92.87940939]

[ 0  1  1 -1  0  1] RIGHT 1
[ -1.1          1.06184789  -1.1         -0.54310477 -10.1
 -92.39204753]

[ 0  1 -1  0  1  0] LEFT 3
[  0.7          1.17537777   0.7          4.92058245  -8.3
 -94.41716211]

[ 0  1 -1  1  0  1] LEFT 3
[  0.69999994   0.48159449   0.69999993   2.31100928  -8.30026423
 -92.52730247]

[ 0  1 -1 -1  0  1] LEFT 3
[  0.7          1.12539555   0.7          2.11437647  -8.3
 -92.88787812]

[ 1  0  0 -1  0  1] UP 0
[  3.10416291  -2.          -1.51175696  -2.         -11.
 -99.51926028]

[ 1  0  1 -1  0  1] UP 0
[  1.4         -1.99999991  -0.5156694   -1.99999999 -10.99991706
 -99.71699886]

[ 1  0 -1  0  1  0] DOWN 2
[  0.30421883  -0.20000104   1.25873301  -0.20000225  -9.20133861
 -92.83318702]

[ 1  0 -1  1  0  1] DOWN 2
[  0.30809103  -0.2          2.73270553  -0.2         -9.2
 -90.58763159]

[ 1  0 -1 -1  0  1] UP 0
[   3.2          -2.            1.22538

array([ -92.69750036, -282.22894881,    3.39024631, -284.09023188,
       -110.0057779 ,  -99.85445947])

In [9]:
len(model) # 647

28

In [10]:
a =[1, 2, 3, 4, 5, 6, 7, 8]

for e in a[0:-1]:
    print(e)

1
2
3
4
5
6
7
