In [9]:
import pickle
import numpy as np
ACTIONS = ['UP', 'RIGHT', 'DOWN', 'LEFT', 'WAIT', 'BOMB']
ACTION_TO_INT = {'UP':0, 'RIGHT':1, 'DOWN':2, 'LEFT':3, 'WAIT':4, 'BOMB':5}

# model stats
N_GAMES = "N_GAMES"
N_MOVES = "N_MOVES"

In [22]:
with open("my-saved-model.pt", "rb") as file:
    model:dict = dict(pickle.load(file))

print("number of states: ", len(model))
print("played training games: ", model[N_GAMES])
print("played training moves: ", model[N_MOVES])

EOFError: Ran out of input

In [3]:

for key in model.keys():
    #print(key)
    # action = model[key].argmax()
    #print(key, ACTIONS[action], action)
    print(model[key] )
    print()


5679623 -3.34991859 -1.55359292 -9.57687613]

[0.78448811 1.05086135 1.00342732 0.97511346 1.03905526 1.06437112]

[ 0.15363541 -0.54810778  0.44440837 -0.386282    0.12489214 -4.29277278]

[1.08679568 1.01815811 1.08419767 1.08666745 1.0300286  1.01886878]

[ 1.0029948  -0.46284014  1.02000439  1.04385195  1.05987166 -4.30587314]

[ 0.46168143 -0.49715907  1.0494443  -1.70421209  0.13833821 -4.31664335]

[-0.36209073 -0.84595539 -0.46691713 -0.75990803 -0.79052654 -4.31599763]

[ 0.14930903 -0.49813752  0.39099808 -0.41752291  0.16764012 -4.3524805 ]

[ 0.24119045 -0.49808064  0.03910253 -1.81257158  0.17011102 -4.37236816]

[-0.51657777  1.10199494  1.03236348  1.00473563  1.06086724  1.01956784]

[-0.53267788  1.16153448 -1.92139881  0.41174651  0.16080654 -4.28090869]

[ 1.00348474 -0.50175806  1.17338515  1.01170946  0.14983767 -4.29919302]

[1.07341884 1.05731155 1.05544077 1.08778886 1.0998871  1.06852375]

[1.03337541 0.08166866 1.25154418 1.03784703 0.16921384 1.01431768]

[ 1

KeyboardInterrupt: 

In [ ]:
coins = [(1, 2), (6, 1)]
(x,y) = (1,1)

In [ ]:
def get_direction_from_to(p1:tuple, p2:tuple, max_c:int=2)->tuple:
    try:
        # compute coordinates of vector from p1 to p2 and limit coordinates by max_c
        a = max(min( p2[0]-p1[0], max_c), -max_c)
        b = max(min( p2[1]-p1[1], max_c), -max_c)
    except:
        return (None, None)
    return (a, b)

In [ ]:
def manhattenDist(p1, p2):
    try:
        return np.abs( p1[0]-p2[0] ) + np.abs( p1[1]-p2[1] )
    except:
        return None

In [ ]:
def create_coin_radar(coins, pos, max_dist=np.inf):
    rev_sorted_coins = coins.copy()
    rev_sorted_coins.sort(reverse=True, key=lambda a: manhattenDist(a, pos))
    radar = np.zeros((3,3))
    for coin in rev_sorted_coins:
        v = get_direction_from_to(pos, coin, 1)
        d = min(manhattenDist(coin, pos), max_dist)
        radar[v[0]+1,v[1]+1] = d
    return radar

In [ ]:
create_coin_radar(coins, (x,y), max_dist=5 )

In [ ]:
manhattenDist((1,1),(1,5))