In [71]:
import pickle
import numpy as np
ACTIONS = ['UP', 'RIGHT', 'DOWN', 'LEFT', 'WAIT', 'BOMB']
ACTION_TO_INT = {'UP':0, 'RIGHT':1, 'DOWN':2, 'LEFT':3, 'WAIT':4, 'BOMB':5}

# model stats
N_GAMES = "N_GAMES"
N_MOVES = "N_MOVES"

SyntaxError: invalid syntax (<ipython-input-71-48e977513ce6>, line 3)

In [48]:
batches = dict()
for a in ACTIONS:
    X = [0, 1, 2, 3, 4, 5]
    Y = 1
    batches[a] = [[X, Y], [X, Y], [X, Y]]


for (X, Y) in batches[a]:
    print(X)
    print(Y)
    print()


[0, 1, 2, 3, 4, 5]
1

[0, 1, 2, 3, 4, 5]
1

[0, 1, 2, 3, 4, 5]
1



In [53]:
a = np.array([1, 2])
a = np.array([1, 2, 3])
a

array([1, 2, 3])

In [3]:
with open("my-saved-model.pt", "rb") as file:
    model:dict = dict(pickle.load(file))

print("number of states: ", len(model))
print("played training games: ", model[N_GAMES])
print("played training moves: ", model[N_MOVES])

number of states:  4
played training games:  1
played training moves:  10


In [58]:
with open("action_vectors.pt", "rb") as file:
    action_vectors:dict = dict(pickle.load(file))

for key in action_vectors:
    print(key, action_vectors[key])
    print()

UP [-4.85043049e+11 -2.22992243e+11 -4.52991613e+11 -4.33383020e+11
  1.04546289e+00 -4.29113243e+10 -5.17335044e+11 -3.29240125e+11
 -4.85906402e+11  3.65003581e+11  7.37863899e+11  8.28138605e+11
  4.53500887e+10  1.06651888e+00  7.15744812e+11  1.75043174e+10
  1.31308532e+11  7.09400386e+11]

RIGHT [-0.65465955  0.92308063 -3.45899708 -2.18844523  1.01865906 -3.13627028
 -0.68923628  1.63234283 -3.43707759  4.67707094 -0.8862598   0.75616678
  7.94468018  1.04326819 -1.25338332 13.03761254  3.4009136  -5.58507599]

DOWN [ 2.21884267  2.21140933  2.19149602  1.07961457  1.0616488   2.240715
  2.27513139  1.05330068  2.26743464  1.07027902  1.02541254  1.07868835
 -6.4492847   1.01623417  1.00437696 -6.45744174 -1.64259865  1.03036322]

LEFT [ 2.3549999   2.3356299   2.34776487  2.32367559  1.00891351  1.04554775
  2.32503241  1.06617232  2.32819754  1.00315739  1.04585286  1.09492224
  1.01450304  1.02685032  1.0478177   1.07633317 -6.95793346 -6.95098724]

WAIT [ 2.76209407  1.8502

In [4]:

for key in model.keys():
    #print(key)
    # action = model[key].argmax()
    #print(key, ACTIONS[action], action)
    print(model[key] )
    print()


1

10

[-0.03883035  0.60957913  1.00874326 -0.42526464  1.00561309  1.02943731]

[-0.58689021  1.00348574 -0.50302108  0.65961525  0.11030102 -4.33961594]



In [5]:
coins = [(1, 2), (6, 1)]
(x,y) = (1,1)

In [6]:
def get_direction_from_to(p1:tuple, p2:tuple, max_c:int=2)->tuple:
    try:
        # compute coordinates of vector from p1 to p2 and limit coordinates by max_c
        a = max(min( p2[0]-p1[0], max_c), -max_c)
        b = max(min( p2[1]-p1[1], max_c), -max_c)
    except:
        return (None, None)
    return (a, b)

In [7]:
def manhattenDist(p1, p2):
    try:
        return np.abs( p1[0]-p2[0] ) + np.abs( p1[1]-p2[1] )
    except:
        return None

In [8]:
def create_coin_radar(coins, pos, max_dist=np.inf):
    rev_sorted_coins = coins.copy()
    rev_sorted_coins.sort(reverse=True, key=lambda a: manhattenDist(a, pos))
    radar = np.zeros((3,3))
    for coin in rev_sorted_coins:
        v = get_direction_from_to(pos, coin, 1)
        d = min(manhattenDist(coin, pos), max_dist)
        radar[v[0]+1,v[1]+1] = d
    return radar

In [9]:
create_coin_radar(coins, (x,y), max_dist=5 )

array([[0., 0., 0.],
       [0., 0., 1.],
       [0., 5., 0.]])

In [10]:
manhattenDist((1,1),(1,5))

4